server {
    listen 80;

    resolver 127.0.0.11 valid=10s;

    location = /send {
        return 301 /send/;
    }

    location ^~ /send/ {
        set $form http://fs-form:80;
        rewrite ^/send/(.*)$ /$1 break;
        proxy_pass $form;
    }

    location /api {
        set $backend http://backend:8080;
        proxy_pass $backend;
    }

    location / {
        set $table http://fs-table:80;
        proxy_pass $table;
    }
}