// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api": {
            "get": {
                "description": "Возвращает список отзывов с поддержкой пагинации, поиска и сортировки",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedbacks"
                ],
                "summary": "Получить список отзывов",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Сколько записей пропустить (offset)",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Сколько записей вернуть (limit)",
                        "name": "take",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Поисковый запрос",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Учитывать регистр при поиске",
                        "name": "caseSensitive",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": false,
                        "description": "Искать только целые слова",
                        "name": "wholeWord",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_feedback.FeedbacksResponse"
                        }
                    },
                    "400": {
                        "description": "Неверные параметры запроса",
                        "schema": {
                            "$ref": "#/definitions/internal_feedback.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_feedback.HTTPError"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает новый отзыв в базе данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feedbacks"
                ],
                "summary": "Добавить новый отзыв",
                "parameters": [
                    {
                        "description": "Данные отзыва",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_feedback.Feedback"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_feedback.Feedback"
                        }
                    },
                    "400": {
                        "description": "Неверные параметры запроса",
                        "schema": {
                            "$ref": "#/definitions/internal_feedback.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/internal_feedback.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_feedback.Feedback": {
            "type": "object",
            "required": [
                "rating"
            ],
            "properties": {
                "date_time": {
                    "type": "string",
                    "example": "2026-03-25T14:30:00Z"
                },
                "feedback_text": {
                    "type": "string",
                    "example": "Отличный сервис!"
                },
                "id": {
                    "type": "string",
                    "example": "1105"
                },
                "rating": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "internal_feedback.FeedbacksResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_feedback.Feedback"
                    }
                },
                "total": {
                    "type": "integer",
                    "example": 150
                },
                "totalPages": {
                    "type": "integer",
                    "example": 15
                }
            }
        },
        "internal_feedback.HTTPError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Сообщение об ошибке"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:2510",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Feedback System API",
	Description:      "API сервиса для сбора и отображения отзывов.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
